compThemeSettings As CanvasComponent:
    BlockWidth: =250
    Fill: =RGBA(0, 0, 0, 0)
    Height: =compThemeSettings.SettingsHeight
    SettingsHeight: =270
    SettingsWidth: =1366
    Width: =compThemeSettings.SettingsWidth
    X: =0
    Y: =0
    ZIndex: =3

    conSettingsThemeSelection_Settings As groupContainer.horizontalAutoLayoutContainer:
        DropShadow: =DropShadow.None
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Center
        LayoutDirection: |-
            =Switch(
                App.ActiveScreen.Size,
                ScreenSize.Small,
               LayoutDirection.Vertical,
                LayoutDirection.Horizontal
            )
        LayoutGap: |-
            =Switch(
                App.ActiveScreen.Size,
                ScreenSize.Small,
                10,
                ScreenSize.Medium,
                10,
                ScreenSize.Large,
                10,
                0
            )
        LayoutJustifyContent: =LayoutJustifyContent.Center
        LayoutMode: =LayoutMode.Auto
        PaddingBottom: |-
            =Switch(
                App.ActiveScreen.Size,
                ScreenSize.Small,
               20,
               20
            )
        PaddingTop: =20
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Width: =Parent.Width
        ZIndex: =1

        conLightTheme_Settings As groupContainer.manualLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            DropShadow: =DropShadow.None
            Fill: =ColorValue(varThemeColors.backgroundFill)
            FillPortions: =0
            Height: |-
                =Switch(
                    App.ActiveScreen.Size,
                    ScreenSize.Small,
                    (Parent.Height - Parent.PaddingTop - Parent.PaddingBottom) / 3,
                    Parent.Height - Parent.PaddingTop - Parent.PaddingBottom
                )
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: |-
                =Switch(
                    App.ActiveScreen.Size,
                    ScreenSize.Small,
                    Parent.Width - Parent.PaddingLeft - Parent.PaddingRight,
                    ScreenSize.Medium,
                    Parent.Width / 3 - Parent.LayoutGap,
                    ScreenSize.Large,
                    Parent.Width / 4 - Parent.LayoutGap,
                    Parent.Width / 6 - Parent.LayoutGap
                )
            ZIndex: =1

            lblLightTheme_Settings As label:
                Align: |-
                    =Switch(
                        App.ActiveScreen.Size,
                        1,
                        Align.Left,
                        2,
                        Align.Center,
                        Align.Center
                    )
                AutoHeight: =true
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =ColorValue(varThemeColors.text)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.focusBorder)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Font: =varThemeFont.H3.face
                FontWeight: =varThemeFont.H3.weightBold
                Height: =Self.Size * 2.5    
                Italic: =varThemeFont.H3.italic
                PaddingBottom: =10
                PaddingLeft: =0
                PaddingTop: =0
                Role: =TextRole.Heading3
                Size: =varThemeFont.H3.size
                Text: ="Light Theme"
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.Width
                X: |-
                    =If(
                        App.ActiveScreen.Size < 2,
                        imgLightTheme_Settings.Width + imgLightTheme_Settings.X + 10,
                        0
                    )
                Y: |-
                    =If(
                        App.ActiveScreen.Size < 2,
                        imgLightTheme_Settings.Height / 2 + imgLightTheme_Settings.Y,
                        Parent.Height - Self.Height
                    )
                ZIndex: =1

            imgLightTheme_Settings As image:
                AccessibleLabel: ="Light Theme"
                BorderColor: =ColorValue(varThemeColors.primary)
                BorderThickness: =If(varThemeColors.name="light", 2,0)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledFill: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.focusBorder)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Height: |-
                    =Switch(
                        App.ActiveScreen.Size,
                        1,
                        100,
                        2,
                        100,
                        150
                    )
                HoverBorderColor: =ColorValue(varThemeColors.primary)
                HoverFill: =RGBA(0, 0, 0, 0)
                Image: =imgSettingsLight
                OnSelect: =Set(varThemeColors, varLightTheme)
                PressedBorderColor: =ColorValue(varThemeColors.primary)
                PressedFill: =RGBA(0, 0, 0, 0)
                TabIndex: =0
                Width: =Self.Height
                X: |-
                    =
                    Switch(App.ActiveScreen.Size,
                    1, (Parent.Width) /2 - Self.Width,
                    Parent.Width / 2 - Self.Width / 2)
                Y: |-
                    =Switch(App.ActiveScreen.Size,
                    2, 35, 
                    1, 20,
                    Parent.Height*.1)
                ZIndex: =2

        contDarkTheme_Settings As groupContainer.manualLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            DropShadow: =DropShadow.None
            Fill: =ColorValue(varThemeColors.backgroundFill)
            FillPortions: =0
            Height: |-
                =Switch(
                    App.ActiveScreen.Size,
                    ScreenSize.Small,
                    (Parent.Height - Parent.PaddingTop - Parent.PaddingBottom) / 3,
                    Parent.Height - Parent.PaddingTop - Parent.PaddingBottom
                )
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: |-
                =Switch(
                    App.ActiveScreen.Size,
                    ScreenSize.Small,
                    Parent.Width - Parent.PaddingLeft - Parent.PaddingRight,
                    ScreenSize.Medium,
                    Parent.Width / 3 - Parent.LayoutGap,
                    ScreenSize.Large,
                    Parent.Width / 4 - Parent.LayoutGap,
                    Parent.Width / 6 - Parent.LayoutGap
                )
            ZIndex: =2

            lblDarkTheme_Settings As label:
                Align: |-
                    =Switch(
                        App.ActiveScreen.Size,
                        1,
                        Align.Left,
                        2,
                        Align.Center,
                        Align.Center
                    )
                AutoHeight: =true
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =ColorValue(varThemeColors.text)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.focusBorder)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Font: =varThemeFont.H3.face
                FontWeight: =varThemeFont.H3.weightBold
                Height: =Self.Size * 2.5    
                Italic: =varThemeFont.H3.italic
                PaddingBottom: =10
                PaddingLeft: =0
                PaddingTop: =0
                Role: =TextRole.Heading3
                Size: =varThemeFont.H3.size
                Text: ="Dark Theme"
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.Width
                X: |-
                    =If(
                        App.ActiveScreen.Size < 2,
                        imgLightTheme_Settings.Width + imgLightTheme_Settings.X + 10,
                        0
                    )
                Y: |-
                    =If(
                        App.ActiveScreen.Size < 2,
                        imgDarkTheme_Settings.Height / 2 + imgDarkTheme_Settings.Y,
                        Parent.Height - Self.Height
                    )
                ZIndex: =1

            imgDarkTheme_Settings As image:
                AccessibleLabel: ="Dark Theme"
                BorderColor: =ColorValue(varThemeColors.primary)
                BorderThickness: =If(varThemeColors.name="dark", 2,0)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledFill: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.focusBorder)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Height: |-
                    =Switch(
                        App.ActiveScreen.Size,
                        1,
                        100,
                        2,
                        100,
                        150
                    )
                HoverBorderColor: =ColorValue(varThemeColors.primary)
                HoverFill: =RGBA(0, 0, 0, 0)
                Image: =imgSettingsDark
                OnSelect: =Set(varThemeColors, varDarkTheme)
                PressedBorderColor: =ColorValue(varThemeColors.primary)
                PressedFill: =RGBA(0, 0, 0, 0)
                TabIndex: =0
                Width: =Self.Height
                X: |-
                    =
                    Switch(App.ActiveScreen.Size,
                    1, (Parent.Width) /2 - Self.Width,
                    Parent.Width / 2 - Self.Width / 2)
                Y: |-
                    =Switch(App.ActiveScreen.Size,
                    2, 35, 
                    1, 10,
                    Parent.Height*.1)
                ZIndex: =2

        conContrastTheme_Settings As groupContainer.manualLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            DropShadow: =DropShadow.None
            Fill: =ColorValue(varThemeColors.backgroundFill)
            FillPortions: =0
            Height: |-
                =Switch(
                    App.ActiveScreen.Size,
                    ScreenSize.Small,
                    (Parent.Height - Parent.PaddingTop - Parent.PaddingBottom) / 3,
                    Parent.Height - Parent.PaddingTop - Parent.PaddingBottom
                )
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: |-
                =Switch(
                    App.ActiveScreen.Size,
                    ScreenSize.Small,
                    Parent.Width - Parent.PaddingLeft - Parent.PaddingRight,
                    ScreenSize.Medium,
                    Parent.Width / 3 - Parent.LayoutGap,
                    ScreenSize.Large,
                    Parent.Width / 4 - Parent.LayoutGap,
                    Parent.Width / 6 - Parent.LayoutGap
                )
            ZIndex: =3

            lblContrastTheme_Settings As label:
                Align: |-
                    =Switch(
                        App.ActiveScreen.Size,
                        1,
                        Align.Left,
                        2,
                        Align.Center,
                        Align.Center
                    )
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =ColorValue(varThemeColors.text)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.focusBorder)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Font: =varThemeFont.H3.face
                FontWeight: =varThemeFont.H3.weightBold
                Height: =50
                Italic: =varThemeFont.H3.italic
                PaddingBottom: =10
                PaddingLeft: =0
                PaddingTop: =0
                Role: =TextRole.Heading3
                Size: =varThemeFont.H3.size
                Text: ="Contrast Theme"
                VerticalAlign: =VerticalAlign.Top
                Width: =lblDarkTheme_Settings.Width
                X: |-
                    =If(
                        App.ActiveScreen.Size < 2,
                        imgContrastTheme_Settings.Width + imgContrastTheme_Settings.X + 10,
                        0
                    )
                Y: |-
                    =If(
                        App.ActiveScreen.Size < 2,
                        imgContrastTheme_Settings.Height / 2 + imgContrastTheme_Settings.Y,
                        Parent.Height - Self.Height
                    )
                ZIndex: =1

            imgContrastTheme_Settings As image:
                AccessibleLabel: ="Contrast Theme"
                BorderColor: =ColorValue(varThemeColors.primary)
                BorderThickness: =If(varThemeColors.name="contrast", 2,0)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledFill: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.focusBorder)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Height: |-
                    =Switch(
                        App.ActiveScreen.Size,
                        1,
                        100,
                        2,
                        100,
                        150
                    )
                HoverBorderColor: =ColorValue(varThemeColors.primary)
                HoverFill: =RGBA(0, 0, 0, 0)
                Image: =imgSettingsContrast
                OnSelect: =Set(varThemeColors, varContrastTheme)
                PressedBorderColor: =ColorValue(varThemeColors.primary)
                PressedFill: =RGBA(0, 0, 0, 0)
                TabIndex: =0
                Width: =Self.Height
                X: |-
                    =
                    Switch(App.ActiveScreen.Size,
                    1, (Parent.Width) /2 - Self.Width,
                    Parent.Width / 2 - Self.Width / 2)
                Y: |-
                    =Switch(App.ActiveScreen.Size,
                    2, 35, 
                    1, 10,
                    Parent.Height*.1)
                ZIndex: =2

