"'Settings Screen' As screen":

    mainContainer_settings As groupContainer.verticalAutoLayoutContainer:
        DropShadow: =DropShadow.None
        Fill: =ColorValue(varThemeColors.background)
        Height: =Parent.Height - compHeader_Settings.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        LayoutOverflowY: =LayoutOverflow.Scroll
        PaddingBottom: =40
        PaddingLeft: =40
        PaddingRight: =Self.PaddingLeft
        PaddingTop: =32
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Width: |
            =Parent.Width
        Y: =compHeader_Settings.Y + compHeader_Settings.Height
        ZIndex: =1

        lblSettingsTitle As label:
            Color: =ColorValue(varThemeColors.text)
            FocusedBorderColor: =ColorValue(varThemeColors.primary)
            Font: =varThemeFont.H1.face
            FontWeight: =varThemeFont.H1.weight
            Height: =Self.Size * 2.5    
            Italic: =varThemeFont.H1.italic
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingTop: =0
            Role: =TextRole.Heading1
            Size: =varThemeFont.H1.size
            Text: ="Settings"
            VerticalAlign: =VerticalAlign.Top
            Width: =Parent.Width - Parent.PaddingLeft - Parent.PaddingRight
            ZIndex: =1

        conSettings As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.Start
            Fill: =ColorValue(varThemeColors.backgroundFill)
            FillPortions: =0
            Height: =Parent.Height - Self.Y - Self.PaddingBottom
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutDirection: =LayoutDirection.Vertical
            LayoutGap: =40
            LayoutJustifyContent: =LayoutJustifyContent.Center
            LayoutMinHeight: =Parent.Height
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            LayoutOverflowY: =LayoutOverflow.Scroll
            PaddingBottom: =20
            PaddingLeft: =20
            PaddingRight: |-
                =Switch(App.ActiveScreen.Size,
                5, App.Width - 1580,
                4, 20,
                3, 20,
                2, 20,
                1, 20
                )
            PaddingTop: =20
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: =Parent.Width - Parent.PaddingLeft - Parent.PaddingRight 
            ZIndex: =2

            compThemeSettings_Settings As compThemeSettings:
                BlockWidth: =Self.SettingsHeight * .60
                Height: =compThemeSettings_Settings.SettingsHeight
                LayoutMinHeight: =640
                LayoutMinWidth: =640
                SettingsHeight: |-
                    =
                    
                    If(
                        App.ActiveScreen.Size < ScreenSize.Large,
                        Parent.Height * 0.25,
                        Parent.Height * 0.50
                       
                    )
                SettingsWidth: |-
                    =If(
                        App.ActiveScreen.Size < ScreenSize.Large,
                        Parent.Width - Parent.PaddingLeft - Parent.PaddingRight,
                        Parent.Width * 0.5
                    )
                Width: =compThemeSettings_Settings.SettingsWidth

    compHeader_Settings As compHeader:
        HeaderWidth: =App.Width
        Height: =compHeader_Settings.HeaderHeight
        Width: =compHeader_Settings.HeaderWidth
        ZIndex: =2

