Settings As screen:
    OnVisible: |+
        =UpdateContext(
            {
                _LayoutProperties:
                {
                    outerPadding: {top: 40, right: 40, bottom: 40, left: 40},
                    innerPadding: {top: 20, right: 20, bottom: 20, left: 20},
                    labelPadding: {top: 5, right: 5, bottom: 5, left: 5}
                }
            }
        );
        

    mainContainer_settings As groupContainer.verticalAutoLayoutContainer:
        DropShadow: =DropShadow.None
        Fill: =ColorValue(varThemeColors.background)
        Height: =Parent.Height - compHeader_Settings.Height 
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        LayoutOverflowY: =LayoutOverflow.Scroll
        PaddingBottom: =Self.PaddingTop
        PaddingLeft: |-
            =If(
                App.ActiveScreen.Size < 3,
                _LayoutProperties.outerPadding.top / 5,
                _LayoutProperties.outerPadding.top
            )
        PaddingRight: =Self.PaddingLeft
        PaddingTop: |-
            =If(
                App.ActiveScreen.Size < 3,
                _LayoutProperties.outerPadding.top / 5,
                _LayoutProperties.outerPadding.top / 2
            )
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Width: =Parent.Width
        Y: =compHeader_Settings.Y + compHeader_Settings.Height
        ZIndex: =1

        conSettings_Title As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            DropShadow: =DropShadow.None
            Fill: =ColorValue(varThemeColors.background)
            FillPortions: =0
            Height: =lblSettingsTitle.Height + Self.PaddingBottom
            LayoutDirection: =LayoutDirection.Vertical
            LayoutGap: =40
            LayoutMinHeight: =Parent.Height
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingBottom: =20
            PaddingRight: =
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: =Parent.Width - Parent.PaddingLeft - Parent.PaddingRight
            ZIndex: =2

            lblSettingsTitle As label:
                AutoHeight: =true
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =ColorValue(varThemeColors.text)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.focusBorder)
                FocusedBorderThickness: =4
                Font: =varThemeFont.H1.face
                FontWeight: =varThemeFont.H1.weightBold
                Height: =
                Italic: =varThemeFont.H1.italic
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingTop: =0
                Role: =TextRole.Heading1
                Size: =varThemeFont.H1.size
                Text: ="Settings"
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.Width
                ZIndex: =1

        conSettings As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =ColorValue(varThemeColors.backgroundFill)
            FillPortions: =0
            Height: |-
                =If(    
                    And(App.ActiveScreen.Size = ScreenSize.Small , App.ActiveScreen.Height < 561),
                    560,
                    Parent.Height - conSettings_Title.Height - Parent.LayoutGap - Parent.PaddingBottom - Parent.PaddingTop
                )
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutDirection: =LayoutDirection.Vertical
            LayoutGap: =40
            LayoutJustifyContent: =LayoutJustifyContent.Center
            LayoutMinHeight: |-
                =
                Switch(
                    App.ActiveScreen.Size,
                    ScreenSize.Small,
                   810,
                   Parent.Height - conSettings_Title.Height - (Parent.PaddingTop *2)
                )
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingBottom: =20
            PaddingLeft: =20
            PaddingRight: |-
                =Switch(App.ActiveScreen.Size,
                5, App.Width - 1580,
                4, 20,
                3, 20,
                2, 20,
                1, 20
                )
            PaddingTop: =20
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: =Parent.Width - Parent.PaddingLeft - Parent.PaddingRight
            ZIndex: =3

            compThemeSettings_Settings As compThemeSettings:
                BlockWidth: |-
                    =Switch(
                        App.ActiveScreen.Size,
                        ScreenSize.Small,
                        Parent.Width  - Parent.LayoutGap,
                        ScreenSize.Medium,
                        Parent.Width / 3 - Parent.LayoutGap,
                        ScreenSize.Large,
                        Parent.Width / 6 - Parent.LayoutGap,
                        Parent.Width / 6 - Parent.LayoutGap
                    )
                Height: =compThemeSettings_Settings.SettingsHeight
                LayoutMinHeight: =640
                LayoutMinWidth: =640
                SettingsHeight: |-
                    =If(
                        And(App.ActiveScreen.Size = ScreenSize.Small , App.ActiveScreen.Size < 561),
                        560,
                        270
                    )
                SettingsWidth: =Parent.Width
                Width: =compThemeSettings_Settings.SettingsWidth
                ZIndex: =5

    compHeader_Settings As compHeader:
        HeaderWidth: =Parent.Width
        Height: =compHeader_Settings.HeaderHeight
        Width: =compHeader_Settings.HeaderWidth
        ZIndex: =2

