"'Settings Screen' As screen":

    mainContainer_settings As groupContainer.verticalAutoLayoutContainer:
        Fill: =ColorValue(varThemeColors.background)
        Height: =Parent.Height - comHeader_settings.Height
        LayoutMode: =LayoutMode.Auto
        LayoutOverflowY: =LayoutOverflow.Scroll
        PaddingBottom: =40
        PaddingLeft: =40
        PaddingRight: =Self.PaddingLeft
        PaddingTop: =40
        Width: =Parent.Width - compDetailsLeftNavigation_Settings.Width
        X: =compDetailsLeftNavigation_Settings.Width
        Y: =comHeader_settings.Y + comHeader_settings.Height
        ZIndex: =1

        conSettings As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            DropShadow: =DropShadow.Light
            Fill: =ColorValue(varThemeColors.backgroundFill)
            FillPortions: =0
            Height: =640
            LayoutDirection: =LayoutDirection.Vertical
            LayoutGap: =40
            LayoutMinHeight: =Parent.Height
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            LayoutOverflowY: =LayoutOverflow.Scroll
            PaddingBottom: =20
            PaddingLeft: =20
            PaddingRight: |-
                =Switch(App.ActiveScreen.Size,
                5, App.Width - 1580,
                4, 20,
                3, 20,
                2, 20,
                1, 20
                )
            PaddingTop: =20
            Width: =Parent.Width - Parent.PaddingLeft - Parent.PaddingRight 
            ZIndex: =2

            compThemeSettings_Settings As compThemeSettings:
                BlockWidth: =Parent.Width / 3 - Parent.LayoutGap
                Height: =compThemeSettings_Settings.SettingsHeight
                LayoutMinHeight: =640
                LayoutMinWidth: =640
                SettingsWidth: =Parent.Width*.95
                Width: =compThemeSettings_Settings.SettingsWidth

            lblSettingsTitle As label:
                Color: =ColorValue(varThemeColors.text)
                FocusedBorderColor: =ColorValue(varThemeColors.primary)
                Font: =varThemeFont.H1.face
                FontWeight: =varThemeFont.H1.weight
                Height: =Self.Size * 2.5    
                Italic: =varThemeFont.H1.italic
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingTop: =0
                Role: =TextRole.Heading1
                Size: =varThemeFont.H1.size
                Text: |-
                    =// Define a variable named "Text" with the value "{value}"
                    With(
                        {Text: "Settings"},
                        // Check if a localized text exists for "Text" in the user's preferred language
                        If(
                            // If the localized text is blank, return the default text
                            IsBlank(
                                LookUp(
                                    colUserLocalizedStrings,
                                    'English Value' = Text
                                ).'Localized Value'
                            ),
                            Text,
                            // If a localized text is found, return that instead of the default text
                            LookUp(
                                colUserLocalizedStrings,
                                'English Value' = Text
                            ).'Localized Value'
                        )
                    )
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.Width - Parent.PaddingLeft - Parent.PaddingRight
                ZIndex: =1

    compDetailsLeftNavigation_Settings As LeftNavigation:
        Height: =App.Height-Self.Y
        Width: =compDetailsLeftNavigation_Settings.MenuWidth
        Y: =comHeader_settings.Height
        ZIndex: =2

    comHeader_settings As compHeader:
        Height: =comHeader_settings.HeaderHeight
        Width: =App.Width
        ZIndex: =3

