compThemeSettings As CanvasComponent:
    BlockWidth: =250
    Fill: =RGBA(0, 0, 0, 0)
    Height: |
        =compThemeSettings.SettingsHeight
           
    SettingsHeight: =250
    SettingsWidth: =1366
    Width: =compThemeSettings.SettingsWidth
    X: =0
    Y: =0
    ZIndex: =3

    conSettingsThemeSelection_Settings As groupContainer.horizontalAutoLayoutContainer:
        DropShadow: =DropShadow.None
        Height: =Parent.Height
        LayoutGap: =20
        LayoutJustifyContent: =LayoutJustifyContent.Center
        LayoutMode: =LayoutMode.Auto
        RadiusBottomLeft: =0
        RadiusBottomRight: =0
        RadiusTopLeft: =0
        RadiusTopRight: =0
        Width: =Parent.Width
        ZIndex: =1

        conLightTheme_Settings As groupContainer.manualLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            DropShadow: =DropShadow.None
            Fill: |
                =ColorValue(varThemeColors.backgroundFill)
            FillPortions: =0
            Height: =Parent.Height
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: =Parent.Width / 3 - Parent.LayoutGap
            ZIndex: =1

            lblLightTheme_Settings As label:
                Align: =Align.Center
                AutoHeight: =true
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =ColorValue(varThemeColors.text)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.primary)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Font: =varThemeFont.H3.face
                FontWeight: =varThemeFont.H3.weight
                Height: =Self.Size * 2.5
                Italic: =varThemeFont.H3.italic
                PaddingBottom: =10
                PaddingLeft: =0
                PaddingTop: =0
                Role: =TextRole.Heading3
                Size: |-
                    =If(
                        App.ActiveScreen.Size > ScreenSize.Small,
                      
                        varThemeFont.H3.size,
                          varThemeFont.B2.size
                    )
                Text: ="Light"
                Tooltip: =Self.Text
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.Width
                Y: =Parent.Height - Self.Height
                ZIndex: =1

            imgLightTheme_Settings As image:
                AccessibleLabel: ="Light Theme"
                BorderColor: =ColorValue(varThemeColors.primary)
                BorderThickness: =If(varThemeColors.name="light", 2,0)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledFill: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.info)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Height: =Self.Width
                HoverBorderColor: =ColorValue(varThemeColors.primary)
                HoverFill: =RGBA(0, 0, 0, 0)
                Image: =settingsLight
                OnSelect: =Set(varThemeColors, varLightTheme)
                PressedBorderColor: =ColorValue(varThemeColors.primary)
                PressedFill: =RGBA(0, 0, 0, 0)
                TabIndex: =0
                Tooltip: =Self.AccessibleLabel
                Width: =Min(compThemeSettings.BlockWidth, Parent.Width - (Self.FocusedBorderThickness * 2))
                X: =Parent.Width / 2 - Self.Width / 2
                Y: =Parent.Height*.1
                ZIndex: =2

        contDarkTheme_Settings As groupContainer.manualLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            DropShadow: =DropShadow.None
            Fill: |
                =ColorValue(varThemeColors.backgroundFill)
            FillPortions: =0
            Height: =Parent.Height
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: =Parent.Width / 3 - Parent.LayoutGap
            ZIndex: =2

            lblDarkTheme_Settings As label:
                Align: =Align.Center
                AutoHeight: =true
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =ColorValue(varThemeColors.text)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.primary)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Font: =varThemeFont.H3.face
                FontWeight: =varThemeFont.H3.weight
                Height: =Self.Size * 2.5    
                Italic: =varThemeFont.H3.italic
                PaddingBottom: =10
                PaddingLeft: =0
                PaddingTop: =0
                Role: =TextRole.Heading3
                Size: |-
                    =If(
                        App.ActiveScreen.Size > ScreenSize.Small,
                      
                        varThemeFont.H3.size,
                          varThemeFont.B2.size
                    )
                Text: ="Dark"
                Tooltip: =Self.Text
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.Width
                Y: =Parent.Height - Self.Height
                ZIndex: =1

            imgDarkTheme_Settings As image:
                AccessibleLabel: ="Dark Theme"
                BorderColor: =ColorValue(varThemeColors.primary)
                BorderThickness: =If(varThemeColors.name="dark", 2,0)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledFill: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.info)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Height: =Self.Width
                HoverBorderColor: =ColorValue(varThemeColors.primary)
                HoverFill: =RGBA(0, 0, 0, 0)
                Image: =settingsDark
                OnSelect: =Set(varThemeColors, varDarkTheme)
                PressedBorderColor: =ColorValue(varThemeColors.primary)
                PressedFill: =RGBA(0, 0, 0, 0)
                TabIndex: =0
                Tooltip: =Self.AccessibleLabel
                Width: =Min(compThemeSettings.BlockWidth, Parent.Width - (Self.FocusedBorderThickness * 2))
                X: =Parent.Width / 2 - Self.Width / 2
                Y: =Parent.Height*.1
                ZIndex: =2

        conContrastTheme_Settings As groupContainer.manualLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            DropShadow: =DropShadow.None
            Fill: |
                =ColorValue(varThemeColors.backgroundFill)
            FillPortions: =0
            Height: =Parent.Height
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: =Parent.Width / 3 - Parent.LayoutGap
            ZIndex: =3

            lblContrastTheme_Settings As label:
                Align: =Align.Center
                AutoHeight: =true
                BorderColor: =RGBA(0, 0, 0, 0)
                BorderStyle: =BorderStyle.None
                BorderThickness: =2
                Color: =ColorValue(varThemeColors.text)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.primary)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Font: =varThemeFont.H3.face
                FontWeight: =varThemeFont.H3.weight
                Height: =Self.Size * 2.5    
                Italic: =varThemeFont.H3.italic
                PaddingBottom: =10
                PaddingLeft: =0
                PaddingTop: =0
                Role: =TextRole.Heading3
                Size: |-
                    =If(
                        App.ActiveScreen.Size > ScreenSize.Small,
                      
                        varThemeFont.H3.size,
                          varThemeFont.B2.size
                    )
                Text: ="Contrast"
                Tooltip: =Self.Text
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.Width
                Y: =Parent.Height - Self.Height
                ZIndex: =1

            imgContrastTheme_Settings As image:
                AccessibleLabel: ="Contrast Theme"
                BorderColor: =ColorValue(varThemeColors.primary)
                BorderThickness: =If(varThemeColors.name="contrast", 2,0)
                DisabledBorderColor: =RGBA(0, 0, 0, 0)
                DisabledFill: =RGBA(0, 0, 0, 0)
                FocusedBorderColor: =ColorValue(varThemeColors.info)
                FocusedBorderThickness: =varThemeColors.focusBorderThickness
                Height: =Self.Width
                HoverBorderColor: =ColorValue(varThemeColors.primary)
                HoverFill: =RGBA(0, 0, 0, 0)
                Image: =settingsContrast
                OnSelect: =Set(varThemeColors, varContrastTheme)
                PressedBorderColor: =ColorValue(varThemeColors.primary)
                PressedFill: =RGBA(0, 0, 0, 0)
                TabIndex: =0
                Tooltip: =Self.AccessibleLabel
                Width: =Min(compThemeSettings.BlockWidth, Parent.Width - (Self.FocusedBorderThickness * 2))
                X: =Parent.Width / 2 - Self.Width / 2
                Y: =Parent.Height*.1
                ZIndex: =2

