"'Settings Screen' As screen":
    OnVisible: |-
        =//Local LyoutProperties
        UpdateContext(
            {
                var_LayoutProperties: 
                {
                    outerPadding: {top: 20, right: 20, bottom: 20, left: 20},
                    gap: {singlePX: 1, extraSmall: 5, small: 10, medium: 20, semiLarge:30, large:40},
                    thumbnailHeight : {small: 200, large: 250},
                    blockSize : {small: 75, medium: 100, large: 150}
                }
            }
        );

    comHeader_Settings As compHeader:
        HeaderComponentHeight: =var_LayoutProperties.gap.large + var_LayoutProperties.gap.small
        HeaderComponentWidth: =Parent.Width
        Height: =comHeader_Settings.HeaderComponentHeight
        Width: =comHeader_Settings.HeaderComponentWidth

    conBackground_Settings As groupContainer.horizontalAutoLayoutContainer:
        Height: ='Settings Screen'.Height - comHeader_Settings.Height
        LayoutDirection: |
            =LayoutDirection.Horizontal
        LayoutMode: =LayoutMode.Auto
        LayoutOverflowX: =LayoutOverflow.Scroll
        LayoutOverflowY: =LayoutOverflow.Scroll
        Width: =Parent.Width
        Y: =comHeader_Settings.Y + comHeader_Settings.Height
        ZIndex: =1

        conLeftNavigation_Settings As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.Start
            DropShadow: =DropShadow.None
            FillPortions: =0
            Height: |+
                =Parent.Height
                
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: |-
                =If('Settings Screen'.Size < ScreenSize.Large,
                    56,
                    If(varIsNavExpanded, 223, 56)
                )
            ZIndex: =1

            comLeftNavigation_Settings As compLeftNavigation:
                Height: =Parent.Height
                LayoutMinWidth: =640
                Width: |-
                    =If('Settings Screen'.Size < ScreenSize.Large,
                        varControlLayoutProperties.navigation.collapsedWidth,
                            If(varIsNavExpanded, varControlLayoutProperties.navigation.expandedWidth, varControlLayoutProperties.navigation.collapsedWidth)
                    )

        mainContainer_Settings As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.Start
            DropShadow: =DropShadow.None
            Fill: =ColorValue(varThemeColors.background)
            FillPortions: =0
            Height: =Parent.Height
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =100
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            LayoutOverflowY: =LayoutOverflow.Scroll
            PaddingBottom: =var_LayoutProperties.gap.medium
            PaddingLeft: =If('Settings Screen'.Size <= 3, var_LayoutProperties.gap.small , var_LayoutProperties.gap.large)
            PaddingRight: =If('Settings Screen'.Size <= 3, var_LayoutProperties.gap.small , var_LayoutProperties.gap.large)
            PaddingTop: =If('Settings Screen'.Size <= 3, var_LayoutProperties.gap.small , var_LayoutProperties.gap.medium)
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            Width: |
                =Parent.Width - conLeftNavigation_Settings.Width
            Y: =comHeader_Settings.Y + comHeader_Settings.Height
            ZIndex: =2

            lblPageTitle_Settings As label:
                Color: =ColorValue(varThemeColors.text)
                FocusedBorderColor: =ColorValue(varThemeColors.info)
                Font: =varThemeFont.H1.face
                FontWeight: =varThemeFont.H1.weightSemibold
                Height: =Self.Size * 2.5    
                Italic: =varThemeFont.H1.italic
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =varControlLayoutProperties.label.paddingRight
                PaddingTop: =0
                Role: =TextRole.Heading2
                Size: =varThemeFont.H1.size
                Text: ="Settings"
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.Width  - Parent.PaddingLeft - Parent.PaddingRight
                ZIndex: =1

            conCardContent_Settings As groupContainer.horizontalAutoLayoutContainer:
                AlignInContainer: =AlignInContainer.Center
                BorderStyle: =BorderStyle.None
                DropShadow: =DropShadow.Semilight
                Fill: =ColorValue(varThemeColors.backgroundFill)
                FillPortions: =0
                Height: =Parent.Height - Parent.PaddingTop - Parent.PaddingBottom - lblPageTitle_Settings.Height
                LayoutAlignItems: =LayoutAlignItems.Center
                LayoutDirection: =LayoutDirection.Vertical
                LayoutJustifyContent: =LayoutJustifyContent.Center
                LayoutMinHeight: =100
                LayoutMinWidth: =250
                LayoutMode: =LayoutMode.Auto
                PaddingBottom: =If('Settings Screen'.Size <= 3, var_LayoutProperties.gap.extraSmall , var_LayoutProperties.gap.medium)
                PaddingLeft: =If('Settings Screen'.Size <= 3, var_LayoutProperties.gap.extraSmall , var_LayoutProperties.gap.medium)
                PaddingRight: =If('Settings Screen'.Size <= 3, var_LayoutProperties.gap.extraSmall , var_LayoutProperties.gap.medium)
                PaddingTop: =If('Settings Screen'.Size <= 3, var_LayoutProperties.gap.extraSmall , var_LayoutProperties.gap.medium)
                Width: =Parent.Width - Parent.PaddingLeft - Parent.PaddingRight
                ZIndex: =2

                compThemeSettings_Settings As compThemeSettings:
                    BlockWidth: |-
                        =If(
                            App.ActiveScreen.Size < ScreenSize.Large,
                            If(App.ActiveScreen.Size = ScreenSize.Medium,
                                var_LayoutProperties.blockSize.medium,
                                var_LayoutProperties.blockSize.small
                            )
                            ,
                            var_LayoutProperties.blockSize.large
                        )
                    Height: =compThemeSettings_Settings.SettingsHeight
                    LayoutMinHeight: =640
                    LayoutMinWidth: =640
                    SettingsHeight: |+
                        =If('Settings Screen'.Size < ScreenSize.Large,
                            var_LayoutProperties.thumbnailHeight.small,
                            var_LayoutProperties.thumbnailHeight.large
                        )
                        
                    SettingsWidth: |
                        =If('Settings Screen'.Size <= ScreenSize.Large, 
                            Parent.Width - Parent.PaddingRight - Parent.PaddingLeft , Parent.Width * .7)
                    Width: =compThemeSettings_Settings.SettingsWidth
                    ZIndex: =1

