name: Export To Branch

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "Name of the solutions you would like to export."
        required: true

jobs:
  export-solution:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install PAC CLI
        run: |
          npm install -g @microsoft/powerplatform-cli

      - name: Auth and Run PAC Org Who
        run: |
          pac auth create --kind CDS --url ${{ secrets.POWERPLATFORM_URL }} --username ${{ secrets.POWERPLATFORM_USERNAME }} --password ${{ secrets.POWERPLATFORM_PASSWORD }}
          pac org who
        env:
          POWERPLATFORM_URL: ${{ secrets.POWERPLATFORM_URL }}
          POWERPLATFORM_USERNAME: ${{ secrets.POWERPLATFORM_USERNAME }}
          POWERPLATFORM_PASSWORD: ${{ secrets.POWERPLATFORM_PASSWORD }}