name: Export To Branch

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: "Name of the solutions you would like to export."
        required: true

jobs:
  export-solution:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core environment 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Install PAC CLI
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool

      - name: Auth
        run: |
          pac auth create --kind CDS --url ${{ secrets.POWERPLATFORM_URL }} --username ${{ secrets.POWERPLATFORM_USERNAME }} --password ${{ secrets.POWERPLATFORM_PASSWORD }}
        env:
          POWERPLATFORM_URL: ${{ secrets.POWERPLATFORM_URL }}
          POWERPLATFORM_USERNAME: ${{ secrets.POWERPLATFORM_USERNAME }}
          POWERPLATFORM_PASSWORD: ${{ secrets.POWERPLATFORM_PASSWORD }}

      - name: Run Org Who
        run: |
          pac org who